tasks/install.yml
Due to package lists not being recent in certain szenarios the installation
of the role would fail, as it would not find the upstream `unzip` repository
=> fix: failing installation on ubuntu1604

defaults/main.yml, molecule/default/tests/test_default.py
Promtail 1.4.1 has been released, make it the default version to be installed
=> feat: install promtail 1.4.1 by default

README.md, defaults/main.yml, molecule/default/tests/test_default.py, molecule/latest/tests/test_latest.py, tasks/install.yml, templates/config.j2
Have a default `file_sd` configuration directly integrated in the role to ease the integration with services/roles/applications that need custom configurations
=> Feat add file sd config

handlers/main.yml
The restart handler does not escalate privileges.
I'm seeing this failure on Ubuntu 20.04 LTS.
```
RUNNING HANDLER [promtail : Restart promtail] ***********************************************************
fatal: [loki-monolith-s-instance]: FAILED! => {"changed": false, "msg": "failure 1 during daemon-reload: Failed to reload daemon: Access denied\n"}
```
=> fix: raise privileges of restart handler

README.md, defaults/main.yml
A new release for loki/promtail is out, sync the default version with upstream
Changes the default version to `1.5.0`
=> Promtail 1.5.0

.github/workflows/release.yml
Using grep in pcre mode was a quick and dirty solution, however neading
to deal with multiple matches it became apparent that its easier to
use a simple sed stream to select the first match and then exit
=> fix: use sed to correctly extract only the latest changelog entry

README.md, defaults/main.yml
I want to be able to deploy promtail on arm based systems (i.e. raspberry pi ) with the same role as I would use for my x86 based systems. 
Extend `promtail_dist_url` to utilize the already existing `go_arch` variable in order to map cpu architectures to upstream binary names
closes #22
=> feat: add support for arm architecture

tasks/install.yml
Thank you for writing this role - it saved me a bunch of time writing my own.
I've updated the install tasks to use `{{ go_arch}}` instead of amd64 directly. This should match how the binaries are downloaded - I followed the pattern used in #22.
I have a pi and an old debian-running macbook I ran this updated version against and it appears to successfully install and run promtail on both of the hosts.
=> Replace the rest of the hardcoded references to amd64 with {{ go_arch }}

tasks/install.yml
Have a working CI for the role again
Fixed various linting issues related to not specifying a file permissions
=> fix: specify provide permissions for file related tasks

README.md, defaults/main.yml
As loki 1.6.0 is released so is promtail. 
https://github.com/grafana/loki/releases/tag/v1.6.0
=> chore(binary): update promtail to version 1.6.0

test-requirements.txt
Currently CI is broken to due an issue with a dependency - see https://github.com/ansible-community/molecule/issues/3010
=> CI: fix testing by pinning dependencies

README.md, defaults/main.yml, molecule/default/tests/test_default.py, molecule/latest/tests/test_latest.py, tasks/install.yml
here's a proposal for handling the positions file configuration.
=> Fixes / extends configuration of the positions file

README.md
Related to issue #47, looks like this isn't needed any more.  Taking this out appears to solve my deployment issues.
=> Remove entry parser setting from example config

README.md
Improve the documentation in README so that the links point to the correct aspects
=> doc: correct links to upstream configuration

.github/workflows/release.yml
Have a working release pipeline
Currently the pipeline would only work with single digit versions - this change ensures that also double digit version numbers will work
Solves #53
=> ci: ensure the release version is properly parsed in the release pipeline

README.md, defaults/main.yml, tasks/install.yml
With the `promtail_apt_update_cache` option users can now opt out of
cache updates executed by this role.
This is helpful, since if multiple tasks want to update the
package cache in the same play it will be unecessarily prolonged.
Closes #63 
This should work, but I haven't tested it.
=> Add possibility to opt out of APT cache updates

README.md, defaults/main.yml, molecule/default/tests/test_default.py
Have recent version of grafana promtail running - https://github.com/grafana/loki/releases/tag/v2.4.1
=> chore: bump promtail to 2.4.1

.github/workflows/test.yml, meta/main.yml
This role has been tested and works against Debian Bullseye.  Let others know and include in future CI tests.
=> Update meta and CI to show Debian Bullseye support.

defaults/main.yml, handlers/main.yml, tasks/install.yml, tasks/main.yml
Introduce promtail_systemd_service variable (defaults to promtail). Replace hardcoded references to promtail systemd service with {{ promtail_systemd_service }}.
Needed to configure multiple promtail instances.
=> Add promtail_systemd_service variable (needed to configure multiple promtail instances).

tasks/main.yml
Replaces the use of the deprecated keyword `include` and replaces it with the static `import_tasks`
=> Remove deprecated `include`

defaults/main.yml, tasks/install.yml
- Adds variable `promtail_systemd_service_template_path` for systemd service template file path
Enables the use of a custom systemd service configuration file by providing the path to the custom template.
In our case, we need to add some additional settings in the service file to increase the limit of open files for some hosts that have too many log files.
=> Add variable promtail_systemd_service_template_file for systemd service template file

tasks/preflight.yml
When utilizing run_once in a host batch, where the role is excluded,
the role will fail as the information is not present.
Instead we delegate the task to localhost to run it once and avoid
github rate limit issues
closes #112 #113
=> fix: delegate fetching of version information to localhost

tasks/install.yml
This PR sets the home directory of the promtail user to the `promtail_install_dir` (`/opt/promtail`).
When reverting the installation with ansible a `/` as home could lead to the deletion of the whole system when using [ansible.builtin.user module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html) with:
```yaml
- name: "Remove promtail"
vars:
promtail_system_user: promtail
tasks:
- name: "Remove promtail user"
ansible.builtin.user:
name: "{{ promtail_system_user }}"
state: absent
remove: true  # defaults: false
force: true   # defaults: false
```
This may be a edge case, since ansible defaults are safe. But setting the home to a safer location prevents from deleting the whole root.
=> Set promtail user home to install directory

tasks/install.yml
Fixes #140 
Fixes regression introduced in 835faa8. Changing the users home on existing installations will result in failing the user task with:
```
usermod: user promtail is currently used by process…
```
Since promtail is already running on an existing installation the promtail users home can't be changed without stopping the processes of the user.
Omitting the home attribute will not touch the home of existing promtail users. On new installations it will be set to
`/home/{{ promtail_system_user }}` (`/home/promtail`), which won't be created b/c `createhome: False` is set.
=> Remove home parameter in user task

tasks/preflight.yml
Fail early in the `preflight` part of the role when using `promtail_binary_local_dir` and the binary does not exist.
This prevents performing already changes on the system when we can not reach a desired state without issues
=> fix: fail early when using promtail_binary_local_dir

tasks/preflight.yml
This was introduced in 0c331ed, but later (by mistake?) dropped in aa512cd and as a result this playbook will again hit GitHub rate limits with larger number of hosts.
=> Revert back to fetching of version information from localhost

defaults/main.yml, templates/service.j2
Resolved #187.
`promtail_config_expand_env` variable changed from `"false"` to `False` to avoid templating issue.
`-config.expand-env={{ "true" if promtail_config_expand_env else "false" }}` templating has been simplified, now it's `-config.expand-env={{ promtail_config_expand_env | lower }}`
=> Updated `config.expand-env` related variable and templating

templates/config.j2
In some cases to_nice_yaml splitting long lines (>80 symbols) incorrectly.
<details><summary>Example</summary>
<p>
This block in `promtail_config_scrape_configs` :
```yaml
- job_name: nginx-access
static_configs:
- targets:
- localhost
labels:
job: nginx-access
__path__: <path>
pipeline_stages:
- json:
expressions:
time_local: time
remote_addr: remote_addr
method: method
path: path
query: request_query
status: status
bytes_sent: bytes_sent
body_bytes_sent: body_bytes_sent
upstream_time: upstream_time
request_time: request_time
host: host
protocol: request_proto
http_user_agent: http_user_agent
drop_malformed: true
- labels:
host:
path:
status:
method:
- template:
source: out_msg
template: '{% raw %}{{ .remote_addr }} {{ .protocol }} {{ .method }} {{ .host }}{{ .path }}{{ if ne .query "-" …
```
=> fix: disable long lines splitting in promtail_config_scrape_configs

.github/workflows/test.yml, tox.ini
Improved test matrix to ensure latest ansible-version and more current OS distributions are used for testing
=> ci: bumped ansible test versions and base os versions
